version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    volumes:
      -  /my/own/datadir:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

  api:
    image: node:14-alpine
    tty: true
    volumes:
      - .:/app
      - nodemodules:/usr/src/app/node_modules
    working_dir: /app
    command: npm run dev
    ports:
      - 3000:3000

volumes:
    nodemodules: {}
    
